



<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="utf-8">
    <title>Obsługa błędów - Błędy składniowe, Kody błędów, Wyjątki | chyla.org</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="../../../_static/IBM-Plex-Web-5.2.1/css/ibm-plex-mod.css" type="text/css" />
    <link rel="stylesheet" href="../../../_static/bootstrap-icons-1.4.0/bootstrap-icons.css" type="text/css" />
    <link rel="stylesheet" href="../../../_static/bootswatch-cosmo-4-mod.css" type="text/css" />

	
    <link rel="stylesheet" type="text/css" href="../../../_static/pygments.css" />
    <link rel="stylesheet" type="text/css" href="../../../_static/chyla.css" />
    <link rel="shortcut icon" href="../../../_static/logo-45x45.png"/>
    <script id="documentation_options" data-url_root="../../../" src="../../../_static/documentation_options.js"></script>
    <script data-url_root="../../../" id="documentation_options" src="../../../_static/documentation_options.js"></script>
    <script src="../../../_static/jquery.js"></script>
    <script src="../../../_static/underscore.js"></script>
    <script src="../../../_static/doctools.js"></script>
    <script src="../../../_static/pdfobject/pdfobject.min.js"></script>
    <script src="../../../_static/translations.js"></script> 
  </head>

  <body>
    <nav class="navbar navbar-expand-md fixed-top chyla-navbar-light">
        <div class="navbar-brand-logo">
            <a class="navbar-brand" href="../../../index.html">
                <img src="../../../_static/logo-45x45.png" alt="Logo" id="logo" width="45px" height="45px">
            </a>
        </div>

        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="../../../index.html">Cześć!</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../../index.html">Artykuły</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../../../edukacja/index.html">Edukacja</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../../../repozytorium-pakietow/index.html">Repozytorium</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../../../eduvm/index.html">EduVM</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../../../oprogramowanie/omtt.html">OMTT</a>
            </li>
          </ul>
        </div>

        <div class="navbar-nav navbar-right">
            <div id="searchbox" role="search">
                <div class="searchformwrapper">
                    <form class="search-form" action="../../../search.html" method="get">
                        <div class="input-group">
                            <input id="navbar-search-input" class="form-control" type="text" name="q" placeholder="Szukamy?" aria-label="Search input field">
                            <div class="input-group-append">
                            <button type="submit" class="input-group-text"><i class="bi bi-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <button class="navbar-toggler chyla-navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
             <i class="bi bi-list"></i>
        </button>
</nav>

<div id="navbar-placeholder"></div>
<main>
    <div class="document">
        <div class="container">
            <div class="body" role="main">
                
  <section id="obsluga-bledow-bledy-skladniowe-kody-bledow-wyjatki">
<h1>Obsługa błędów - Błędy składniowe, Kody błędów, Wyjątki<a class="headerlink" href="#obsluga-bledow-bledy-skladniowe-kody-bledow-wyjatki" title="Stały odnośnik do tego nagłówka">¶</a></h1>

<div id="pdfobject-0" class="pdfobject-container"></div>
<script>PDFObject.embed("/_static/files/artykuly/python/python-tutorial/Obsluga-bledow-Bledy-skladniowe-Kody-bledow-Wyjatki.pdf", "#pdfobject-0");</script>
<section id="bledy-skladniowe">
<h2>Błędy składniowe<a class="headerlink" href="#bledy-skladniowe" title="Stały odnośnik do tego nagłówka">¶</a></h2>
<p><strong>Błędy składni</strong> wykrywane są podczas parsowania kodu, czyli analizy jego struktury, weryfikacji składni.</p>
<p>Przykładem takiego błędu jest niepoprawne wcięcie bloku kodu lub brak nawiasów.</p>
<div class="highlight-text notranslate"><div class="highlight"><pre><span></span>&gt;&gt;&gt; x := 4
File &quot;&lt;stdin&gt;&quot;, line 1
    x := 4
    ^
SyntaxError: invalid syntax
</pre></div>
</div>
</section>
<section id="kody-bledow">
<h2>Kody błędów<a class="headerlink" href="#kody-bledow" title="Stały odnośnik do tego nagłówka">¶</a></h2>
<p>Obsługę błędów można realizować za pomocą <strong>kodów błędów</strong>, czyli specjalnych wartości przekazywanych z funkcji do wywołującego, oznaczających wystąpienie błędu podczas jej wykonywania.</p>
<p>Najczęściej kody błędów są implementowane za pomocą liczb całkowitych, chociaż może to być dowolny inny typ (np. napis). Dobrą praktyką jest ich grupowanie za pomocą typów wyliczeniowych.</p>
<p>W najprostszych przypadkach kodami błędów mogą być wartości <code class="docutils literal notranslate"><span class="pre">True</span></code>, <code class="docutils literal notranslate"><span class="pre">False</span></code> przekazywane do wywołującego funkcję za pomocą mechanizmu zwracania wartości.</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="kn">import</span> <span class="nn">string</span>

<span class="k">def</span> <span class="nf">check_digit</span><span class="p">(</span><span class="n">text</span><span class="p">):</span>
    <span class="k">for</span> <span class="n">x</span> <span class="ow">in</span> <span class="n">text</span><span class="p">:</span>
        <span class="k">if</span> <span class="n">x</span> <span class="ow">not</span> <span class="ow">in</span> <span class="n">string</span><span class="o">.</span><span class="n">digits</span><span class="p">:</span>
            <span class="k">return</span> <span class="kc">False</span>
    <span class="k">if</span> <span class="nb">len</span><span class="p">(</span><span class="n">text</span><span class="p">)</span> <span class="o">==</span> <span class="mi">0</span><span class="p">:</span>
        <span class="k">return</span> <span class="kc">False</span>
    <span class="k">return</span> <span class="kc">True</span>
</pre></div>
</div>
<p>Wartości <code class="docutils literal notranslate"><span class="pre">True</span></code>, <code class="docutils literal notranslate"><span class="pre">False</span></code> nie niosą ze sobą informacji powodu z jakiego funkcja się zakończyła. Informują one tylko o tym czy dana funkcja zakończyła się poprawnie czy nie. Bardziej szczegółową informację można zawrzeć w nazwanych kodach błędów.</p>
<p>Kodami błędów mogą być dowolne wartości o określonych nazwach.</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="n">SUCCESS</span> <span class="o">=</span> <span class="mi">0</span>
<span class="n">ERR_FOUND_LETTER</span> <span class="o">=</span> <span class="mi">1</span>
<span class="n">ERR_EMPTY_STRING</span> <span class="o">=</span> <span class="mi">2</span>

<span class="kn">import</span> <span class="nn">string</span>

<span class="k">def</span> <span class="nf">check_digit</span><span class="p">(</span><span class="n">text</span><span class="p">):</span>
    <span class="k">for</span> <span class="n">x</span> <span class="ow">in</span> <span class="n">text</span><span class="p">:</span>
        <span class="k">if</span> <span class="n">x</span> <span class="ow">not</span> <span class="ow">in</span> <span class="n">string</span><span class="o">.</span><span class="n">digits</span><span class="p">:</span>
            <span class="k">return</span> <span class="n">ERR_FOUND_LETTER</span>
    <span class="k">if</span> <span class="nb">len</span><span class="p">(</span><span class="n">text</span><span class="p">)</span> <span class="o">==</span> <span class="mi">0</span><span class="p">:</span>
        <span class="k">return</span> <span class="n">ERR_EMPTY_STRING</span>
    <span class="k">return</span> <span class="n">SUCCESS</span>
</pre></div>
</div>
<p>Stosując typ wyliczeniowy (Enum) można powiązać ze sobą poszczególne kody błędów. Funkcja <code class="docutils literal notranslate"><span class="pre">auto()</span></code> samoczynnie wygeneruje wartość liczbową dla kolejnych kodów.</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="kn">import</span> <span class="nn">string</span>
<span class="kn">from</span> <span class="nn">enum</span> <span class="kn">import</span> <span class="n">Enum</span><span class="p">,</span> <span class="n">auto</span>

<span class="k">class</span> <span class="nc">DigitErrors</span><span class="p">(</span><span class="n">Enum</span><span class="p">):</span>
    <span class="n">SUCCESS</span> <span class="o">=</span> <span class="n">auto</span><span class="p">()</span>
    <span class="n">ERR_FOUND_LETTER</span> <span class="o">=</span> <span class="n">auto</span><span class="p">()</span>
    <span class="n">ERR_EMPTY_STRING</span> <span class="o">=</span> <span class="n">auto</span><span class="p">()</span>

<span class="k">def</span> <span class="nf">check_digit</span><span class="p">(</span><span class="n">text</span><span class="p">):</span>
    <span class="k">for</span> <span class="n">x</span> <span class="ow">in</span> <span class="n">text</span><span class="p">:</span>
        <span class="k">if</span> <span class="n">x</span> <span class="ow">not</span> <span class="ow">in</span> <span class="n">string</span><span class="o">.</span><span class="n">digits</span><span class="p">:</span>
            <span class="k">return</span> <span class="n">DigitErrors</span><span class="o">.</span><span class="n">ERR_FOUND_LETTER</span>
    <span class="k">if</span> <span class="nb">len</span><span class="p">(</span><span class="n">text</span><span class="p">)</span> <span class="o">==</span> <span class="mi">0</span><span class="p">:</span>
        <span class="k">return</span> <span class="n">DigitErrors</span><span class="o">.</span><span class="n">ERR_EMPTY_STRING</span>
    <span class="k">return</span> <span class="n">DigitErrors</span><span class="o">.</span><span class="n">SUCCESS</span>
</pre></div>
</div>
<p>Zastosowanie typu wyliczeniowego pozwoliło na:</p>
<ol class="arabic simple">
<li><p>powiązanie wartości,</p></li>
<li><p>grupowanie kodów przeznaczonych dla danego zastosowania,</p></li>
<li><p>uniemożliwienie porównania różnych rodzajów błędów (np. błąd związany z otwarciem pliku i sprawdzeniem napisu).</p></li>
</ol>
<p><strong>Podsumowanie:</strong></p>
<ul class="simple">
<li><p>obsługa błędu może zostać pominięta świadomie lub nieświadomie,</p></li>
<li><p>odseparowanie kodu obsługującego błędy od kodu wykonującego obliczenia jest trudne,</p></li>
<li><p>obsłużenie błędu w innym miejscu w programie wymaga przekazywania kodu błędu za pomocą zwracanej wartości z kolejnych wywołań funkcji.</p></li>
</ul>
</section>
<section id="wyjatki">
<h2>Wyjątki<a class="headerlink" href="#wyjatki" title="Stały odnośnik do tego nagłówka">¶</a></h2>
<p>Wyjątki są rodzajem błędów wykrytych podczas działania programu.</p>
<p>Przykładem takiego błędu jest dzielenie liczby przez 0.</p>
<div class="highlight-text notranslate"><div class="highlight"><pre><span></span>&gt;&gt;&gt; 2/0
Traceback (most recent call last):
    File &quot;&lt;stdin&gt;&quot;, line 1, in &lt;module&gt;
ZeroDivisionError: division by zero
</pre></div>
</div>
<p>Wyjątek jest obiektem będącym instancją klasy <code class="docutils literal notranslate"><span class="pre">BaseException</span></code>, obowiązuje ustalona hierarchia wyjątków.</p>
<div class="highlight-text notranslate"><div class="highlight"><pre><span></span>BaseException
+-- SystemExit
+-- KeyboardInterrupt
...
+-- Exception
...
    +-- ArithmeticError
    |    +-- FloatingPointError
    |    +-- OverflowError
    |    +-- ZeroDivisionError
    +-- AssertionError
...
    +-- ImportError
    |    +-- ModuleNotFoundError
...
    +-- RuntimeError
    |    +-- NotImplementedError
    |    +-- RecursionError
    +-- SyntaxError
    |    +-- IndentationError
    |         +-- TabError
...
    +-- ValueError
...
</pre></div>
</div>
<p><strong>Wyjątki mogą być przechwycone</strong>, czyli w pewien sposób przewidziane i obsłużone przez programistę. W tym celu powstała specjalna składnia try-except-else-finally.</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="c1"># kod, w którym może wystąpić wyjątek</span>
<span class="k">except</span> <span class="n">KlasaOczekiwanegoWyjatku</span> <span class="k">as</span> <span class="n">nazwa</span><span class="p">:</span>
    <span class="c1"># kod obsługujący sytuację, gdy wystąpił</span>
    <span class="c1"># podany wyjątek</span>
<span class="k">except</span> <span class="n">InnaKlasaOczekiwanegoWyjatku</span> <span class="k">as</span> <span class="n">nazwa</span><span class="p">:</span>
    <span class="c1"># kod obsługujący sytuację, gdy wystąpił</span>
    <span class="c1"># podany wyjątek</span>
<span class="k">else</span><span class="p">:</span>
    <span class="c1"># kod wykonywany, gdy wyjątek nie wystąpił</span>
<span class="k">finally</span><span class="p">:</span>
    <span class="c1"># kod wykonywany zawsze</span>
</pre></div>
</div>
<p>Wystąpienie sytuacji wyjątkowej powoduje <strong>przerwanie wykonywania kodu</strong> umieszczonego w bloku try.</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Proba dzielenia przez 0.&quot;</span><span class="p">)</span>
    <span class="n">x</span> <span class="o">=</span> <span class="mi">2</span> <span class="o">/</span> <span class="mi">0</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Wynik operacji:&quot;</span><span class="p">,</span> <span class="n">x</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">ArithmeticError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Zlapano wyjatek:&quot;</span><span class="p">,</span> <span class="n">e</span><span class="p">)</span>
</pre></div>
</div>
<p>W podanym przykładzie zostanie rzucony wyjątek w wyniku próby podzielenia liczby przez 0. Na ekranie pojawi się komunikat o próbie dzielenia oraz informacja o przechwyceniu wyjątku.</p>
<p>Wyjątek może zostać rzucony również w przypadku próby dokonania niedozwolonej konwersji typów - np. zamiany napisu na liczbę.</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Proba zamiany napisu &#39;E&#39; na liczbę.&quot;</span><span class="p">)</span>
    <span class="n">x</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="s1">&#39;E&#39;</span><span class="p">)</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Wynik operacji:&quot;</span><span class="p">,</span> <span class="n">x</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">ValueError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Zlapano wyjatek:&quot;</span><span class="p">,</span> <span class="n">e</span><span class="p">)</span>
</pre></div>
</div>
<p>Rzucone wyjątki powodują przerwanie wykonywania wszystkich funkcji z sekwencji wywołań, aż do napotkania bloku try-except-else-finally, jeśli nie zostanie on napotkany następuje przerwanie wykonywania programu.</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">f</span><span class="p">():</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Proba zamiany napisu &#39;E&#39; na liczbę.&quot;</span><span class="p">)</span>
    <span class="n">x</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="s1">&#39;E&#39;</span><span class="p">)</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Wynik operacji:&quot;</span><span class="p">,</span> <span class="n">x</span><span class="p">)</span>

<span class="k">def</span> <span class="nf">g</span><span class="p">():</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Wywoluje f()&quot;</span><span class="p">)</span>
    <span class="n">f</span><span class="p">()</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Zakonczono f()&quot;</span><span class="p">)</span>

<span class="k">try</span><span class="p">:</span>
    <span class="n">g</span><span class="p">()</span>
<span class="k">except</span> <span class="ne">ValueError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Zlapano wyjatek:&quot;</span><span class="p">,</span> <span class="n">e</span><span class="p">)</span>
</pre></div>
</div>
<p><strong>Blok else</strong> jest wykonywany tylko w przypadku, gdy wyjątek nie został rzucony. W przytoczonym przykładzie na ekranie pojawi się:</p>
<div class="highlight-text notranslate"><div class="highlight"><pre><span></span>Proba zamiany napisu &#39;15&#39; na liczbę.
Wynik operacji: 15
Wyjątek nie wystapil
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Proba zamiany napisu &#39;15&#39; na liczbę.&quot;</span><span class="p">)</span>
    <span class="n">x</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="s1">&#39;15&#39;</span><span class="p">)</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Wynik operacji:&quot;</span><span class="p">,</span> <span class="n">x</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">ArithmeticError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Zlapano wyjatek:&quot;</span><span class="p">,</span> <span class="n">e</span><span class="p">)</span>
<span class="k">else</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Wyjątek nie wystapil&quot;</span><span class="p">)</span>
</pre></div>
</div>
<p>Kod umieszczony w <strong>bloku finally</strong> jest wykonywany zawsze, niezależnie od tego, czy wyjątek został rzucony, czy nie.</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Proba zamiany napisu &#39;15&#39; na liczbę.&quot;</span><span class="p">)</span>
    <span class="n">x</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="s1">&#39;15&#39;</span><span class="p">)</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Wynik operacji:&quot;</span><span class="p">,</span> <span class="n">x</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">ArithmeticError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Zlapano wyjatek:&quot;</span><span class="p">,</span> <span class="n">e</span><span class="p">)</span>
<span class="k">finally</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Blok kodu wykonywany zawsze.&quot;</span><span class="p">)</span>
</pre></div>
</div>
<p><strong>Pytanie:</strong></p>
<p>Czy w przypadku wykonania instrukcji <code class="docutils literal notranslate"><span class="pre">return</span></code> blok <code class="docutils literal notranslate"><span class="pre">finally</span></code> również zostanie wykonany?</p>
<p><em>Zwróćmy uwagę na instrukcję ``return`` zwracającą podaną wartość z funkcji.</em></p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">funkcja</span><span class="p">():</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Proba zamiany napisu &#39;15&#39; </span><span class="se">\</span>
<span class="s2">na liczbę.&quot;</span><span class="p">)</span>
        <span class="n">x</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="s1">&#39;15&#39;</span><span class="p">)</span>
        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Wynik operacji:&quot;</span><span class="p">,</span> <span class="n">x</span><span class="p">)</span>
        <span class="k">return</span> <span class="n">x</span>
    <span class="k">except</span> <span class="ne">ArithmeticError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Zlapano wyjatek:&quot;</span><span class="p">,</span> <span class="n">e</span><span class="p">)</span>
    <span class="k">finally</span><span class="p">:</span>
        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Blok kodu wykonywany zawsze.&quot;</span><span class="p">)</span>
        <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;ale czy na pewno?&quot;</span><span class="p">)</span>

<span class="n">funkcja</span><span class="p">()</span>
</pre></div>
</div>
<p><strong>TAK</strong>, blok <code class="docutils literal notranslate"><span class="pre">finally</span></code> zostanie wykonany.</p>
<p><strong>Blok finally może występować razem z blokiem try</strong> (pominięta konstrukcja except). Na ekranie zobaczymy:</p>
<div class="highlight-text notranslate"><div class="highlight"><pre><span></span>Proba zamiany napisu &#39;15&#39; na liczbę.
Wynik operacji: 15
Blok kodu wykonywany zawsze.
</pre></div>
</div>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Proba zamiany napisu &#39;15&#39; na liczbę.&quot;</span><span class="p">)</span>
    <span class="n">x</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="s1">&#39;15&#39;</span><span class="p">)</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Wynik operacji:&quot;</span><span class="p">,</span> <span class="n">x</span><span class="p">)</span>
<span class="k">finally</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Blok kodu wykonywany zawsze.&quot;</span><span class="p">)</span>
</pre></div>
</div>
<p><strong>Pominięcie bloku except w przypadku konstrukcji else jest nieprawidłowe.</strong></p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>  <span class="c1"># TO NIE ZADZIAŁA!</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Proba zamiany napisu &#39;15&#39; na liczbę.&quot;</span><span class="p">)</span>
    <span class="n">x</span> <span class="o">=</span> <span class="nb">int</span><span class="p">(</span><span class="s1">&#39;15&#39;</span><span class="p">)</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Wynik operacji:&quot;</span><span class="p">,</span> <span class="n">x</span><span class="p">)</span>
<span class="k">else</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="s2">&quot;Wyjątek nie wystapil&quot;</span><span class="p">)</span>
</pre></div>
</div>
<p>O rzuceniu wyjątku może zdecydować programista wykorzystując instrukcję <code class="docutils literal notranslate"><span class="pre">raise</span></code>.</p>
<p>Argumentem do instrukcji jest obiekt będący instancją klasy reprezentującej odpowiednią klasę błędu.</p>
<p>Wyjątki rzucone przez programistę również mogą zostać przechwycone za pomocą bloku try-except-else-finally.</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="kn">import</span> <span class="nn">string</span>

<span class="k">def</span> <span class="nf">check_digit</span><span class="p">(</span><span class="n">text</span><span class="p">):</span>
    <span class="k">for</span> <span class="n">x</span> <span class="ow">in</span> <span class="n">text</span><span class="p">:</span>
        <span class="k">if</span> <span class="n">x</span> <span class="ow">not</span> <span class="ow">in</span> <span class="n">string</span><span class="o">.</span><span class="n">digits</span><span class="p">:</span>
            <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span><span class="n">x</span> <span class="o">+</span> <span class="s1">&#39; is not a digit&#39;</span><span class="p">)</span>
    <span class="k">if</span> <span class="nb">len</span><span class="p">(</span><span class="n">text</span><span class="p">)</span> <span class="o">==</span> <span class="mi">0</span><span class="p">:</span>
        <span class="k">raise</span> <span class="ne">ValueError</span><span class="p">(</span><span class="s1">&#39;Empty string&#39;</span><span class="p">)</span>

<span class="n">check_digit</span><span class="p">(</span><span class="s1">&#39;5&#39;</span><span class="p">)</span>
<span class="n">check_digit</span><span class="p">(</span><span class="s1">&#39;3a&#39;</span><span class="p">)</span>
</pre></div>
</div>
<p>Wbudowane klasy wyjątków nie zawsze są wystarczające, dlatego <strong>programista ma możliwość utworzenia wyjątku własnej klasy</strong>.</p>
<p>W tym celu należy:</p>
<ol class="arabic simple">
<li><p>określić odpowiedzialność wyjątku, zdefiniować nazwę,</p></li>
<li><p>wybrać klasę nadrzędną,</p></li>
<li><p>utworzyć dokumentację dokumentacji, jeśli istnieje taka potrzeba,</p></li>
<li><p>utworzyć metodę <code class="docutils literal notranslate"><span class="pre">__init__()</span></code>.</p></li>
<li><p>wywołać metodę <code class="docutils literal notranslate"><span class="pre">__init__()</span></code> klasy nadrzędnej.</p></li>
</ol>
<p>Po jakiej klasie dziedziczyć podczas tworzenia własnej klasy wyjątku?</p>
<ul class="simple">
<li><p>BaseException - The base class for all built-in exceptions. <strong>It is not meant to be directly inherited by user-defined classes</strong>.</p></li>
<li><p>Exception - All built-in, non-system-exiting exceptions are derived from this class. All user-defined exceptions should also be derived from this class.</p></li>
</ul>
<p>Opisy odpowiedzialności dla poszczególnych wyjątków: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html">https://docs.python.org/3/library/exceptions.html</a></p>
<p><strong>Wyjątki zdefiniowane przez użytkownika muszą dziedziczyć po klasie Exception - bezpośrednio lub pośrednio za pomocą innej klasy.</strong></p>
<p>Utworzenie nowego rodzaju wyjątku wiąże się z utworzeniem nowej klasy.</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">class</span> <span class="nc">EmptyString</span><span class="p">(</span><span class="ne">ValueError</span><span class="p">):</span>
    <span class="sd">&quot;&quot;&quot;Rzucany, gdy napis jest pusty.&quot;&quot;&quot;</span>
    <span class="k">def</span> <span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="nb">super</span><span class="p">()</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span><span class="s2">&quot;String is empty&quot;</span><span class="p">)</span>

<span class="k">class</span> <span class="nc">NotDigit</span><span class="p">(</span><span class="ne">ValueError</span><span class="p">):</span>
    <span class="sd">&quot;&quot;&quot;Rzucany, gdy napis nie jest cyfrą.&quot;&quot;&quot;</span>
    <span class="k">def</span> <span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">wrong_char</span><span class="p">):</span>
        <span class="nb">super</span><span class="p">()</span><span class="o">.</span><span class="fm">__init__</span><span class="p">(</span><span class="s2">&quot;Not a digit: &quot;</span> <span class="o">+</span> <span class="n">wrong_char</span><span class="p">)</span>
</pre></div>
</div>
<p>Nowo utworzony rodzaj wyjątku może zostać rzucony w taki sam sposób, jak wyjątki wbudowane.</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">check_digit</span><span class="p">(</span><span class="n">string</span><span class="p">):</span>
    <span class="k">for</span> <span class="n">x</span> <span class="ow">in</span> <span class="n">string</span><span class="p">:</span>
        <span class="k">if</span> <span class="n">x</span> <span class="ow">not</span> <span class="ow">in</span> <span class="n">string</span><span class="o">.</span><span class="n">digits</span><span class="p">:</span>
            <span class="k">raise</span> <span class="n">NotDigit</span><span class="p">(</span><span class="n">x</span><span class="p">)</span>
    <span class="k">if</span> <span class="nb">len</span><span class="p">(</span><span class="n">string</span><span class="p">)</span> <span class="o">==</span> <span class="mi">0</span><span class="p">:</span>
        <span class="k">raise</span> <span class="n">EmptyString</span>
</pre></div>
</div>
<p>Istnieje możliwość utworzenia <strong>wielu bloków ``except``, jednak rzucony wyjątek trafi tylko do pierwszego pasującego</strong>.</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="n">check_digit</span><span class="p">(</span><span class="s1">&#39;5&#39;</span><span class="p">)</span>
    <span class="n">check_digit</span><span class="p">(</span><span class="s1">&#39;3a&#39;</span><span class="p">)</span>
<span class="k">except</span> <span class="n">EmptyString</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>
<span class="k">except</span> <span class="n">NotDigit</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>
</pre></div>
</div>
<p><strong>Wyjątki mogą być ze sobą pogrupowane i obsłużone w jednym bloku ``except``.</strong></p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="n">check_digit</span><span class="p">(</span><span class="s1">&#39;5&#39;</span><span class="p">)</span>
    <span class="n">check_digit</span><span class="p">(</span><span class="s1">&#39;3a&#39;</span><span class="p">)</span>
<span class="k">except</span> <span class="p">(</span><span class="n">EmptyString</span><span class="p">,</span> <span class="n">NotDigit</span><span class="p">)</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>
</pre></div>
</div>
<p>Wykorzystując hierarchię klas można przechwycić wyjątek na podstawie klasy nadrzędnej.</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="n">check_digit</span><span class="p">(</span><span class="s1">&#39;5&#39;</span><span class="p">)</span>
    <span class="n">check_digit</span><span class="p">(</span><span class="s1">&#39;3a&#39;</span><span class="p">)</span>
<span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
    <span class="nb">print</span><span class="p">(</span><span class="n">e</span><span class="p">)</span>
</pre></div>
</div>
<p><strong>Podsumowanie:</strong></p>
<ul class="simple">
<li><p><strong>obsługa wyjątku nie może być pominięta</strong>, w przeciwnym wypadku program może przerwać działanie,</p></li>
<li><p>wyjątki powodują przerwanie wykonywania wszystkich funkcji z sekwencji wywołań,</p></li>
<li><p>obsługa wyjątków jest w jasny sposób odizolowana od kodu wykonującego obliczenia,</p></li>
<li><p>wyjątki mogą przechowywać dodatkowe informacje na temat napotkanego błędu.</p></li>
</ul>
</section>
<section id="literatura">
<h2>Literatura<a class="headerlink" href="#literatura" title="Stały odnośnik do tego nagłówka">¶</a></h2>
<ol class="arabic simple">
<li><p><a class="reference external" href="https://docs.python.org/3/tutorial/errors.html">Errors and Exceptions</a></p></li>
</ol>
</section>
</section>


                <div class="clearer"></div>
            </div>
        </div>
    </div>
</main>


    <footer id="footer" class="chyla-footer-light">
        <div class="row">
            <div class="footer-box footer-infos col-md-10">
				
<h5>Adam Chyła</h5>
<p>Klucz GPG: <a href="https://keyserver.ubuntu.com/pks/lookup?search=09C6348C6917D7CDCD74041B53984B48D35B4B7B&fingerprint=on&op=index" target="_blank">09C6348C6917D7CDCD74041B53984B48D35B4B7B</a></p>

            </div>
            <div class="footer-box chyla-footer-social-list col-md-2">
                <h5>Social media</h5>
                <ul>
					
<li><a href="https://github.com/chyla" target="_blank"><i class="bi bi-github"></i></a></li>

				</ul>
            </div>
        </div>

        <div class="row">
            <div class="footer-box footer-law col-md-12">
				
<p>Witryna prywatna. Każda opinia wyrażona w tej wirtynie jest wyłącznie moją opinią (nie jest to opinia mojego pracodawcy).<br/>
   Private website. All opinions expressed here are only mine (not of my employer).</p>

<p><a href="/law/nota_prawna.html">Zapoznaj się z notą prawną dotyczącą treści i funkcjonowania portalu</a> oraz <a href="/law/polityka_prywatnosci_i_plikow_cookies.html">polityką prywatności i plików cookie</a>.</p>

            </div>
        </div>
    </footer>

    <script src="../../../_static/bootstrap-4.6/bootstrap.bundle.min.js"></script>
	
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-DKEWN50PZG"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-DKEWN50PZG');
</script>


  </body>
</html>